### ISSUE TITLE
Visual improvements for edges (patch cables)

### ISSUE THREAD

**Issue by karate** [blibliki-js/grid#14]
Some suggestions are:

- increase width
- add arrow heads (https://reactflow.dev/examples/edges/custom-edges)
- animation (https://reactflow.dev/learn/customization/theming)
- change curve type to `smoothtype` instead of `default` (`bezier`) (https://reactflow.dev/examples/edges/edge-types). This is to prevent overlapping like in the screenshot below ![image](https://github.com/blibliki-js/grid/assets/1358965/99afcb0e-80e5-4278-8cea-fa347209e1b1)

**Comment by karate** [comment]
We're going to skip the animation and arrow heads. It doesn't add anything to the UX, and makes the interface distracting.

**Comment by karate** [comment]
I run some tests and came up with the following changes that seem to improve the UI:
- `smoothtype` instead of the default `bezier` curves, to minimize overlapping.
- thicker patch lines
- better visual cue for the selected patch (when the user clicks on a patch cable). I make it blue to match the controls

Here's some screenshots:
(modules connections doesn't make any sense. I just wanted to highlight a 'complex' setup)

BEFORE:
![before](https://github.com/blibliki-js/grid/assets/1358965/decac2c0-4b6c-4088-a86d-ccf1c42dd535)
AFTER:
![after](https://github.com/blibliki-js/grid/assets/1358965/f20b1d09-cd77-481a-a303-c6235562f349)

**Comment by mikezaby** [comment]
I like it! We could go like this.
